### ISSUE TITLE
rename then-jade to then-pug

### ISSUE THREAD

**Issue by jeromew** [pugjs/then-pug#21]
@ForbesLindesay can you rename then-jade repository to then-pug ? I think I do not have the rights to do it. Thanks.

for info i stored `then-jade` inside the then-jade-legacy branch. 

then-pug is on master as a lerna package (it was easier for me at this stage). I will continue to add tests before publishing a new npm version that will replace the current `then-pug` that I published 2 years ago - https://www.npmjs.com/package/then-pug

**Comment by ForbesLindesay** [comment]
Done.
